apiVersion: v1
kind: persistentVolumeClaim
metadata:
  name: dbpvc
  labels:
    app: vprodb
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: default