apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-wordpress-pvc
spec:
  storageClassName: {{ .Values.wordpress.pvc.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wordpress.pvc.storage }}
